### ISSUE TITLE
Issue with amount of textures allocated

### ISSUE THREAD

**Issue by RumbleballTheReal** [eldskald/planar-reflections-unity#1] opened 2022-10-28 09:52 UTC
The reflection probe allocates a RenderTexture every frame for every camera that needs reflection. Letting the project run for ~30min, issues will appear in the project and log spam that tells not enough object indices.

To solve it, it needs to only allocate a single texture per camera and only replace the texture when something changed, e.g. Texture resolution.

A Dictionary can be used to map the allocated RenderTexture to the Camera.

**Comment by eldskald** [comment] 2023-04-07 04:34
Hey, sorry for not responding earlier, I didn't see this issue before. I tried to reproduce this error but I couldn't. The reason why I made it create a RenderTexture per camera per frame is because it was the easiest way to get the probe to update the resolution without running into memory leaks, using the camera post render to get rid of it was the cleanest way I found.
I'm assuming you fixed this error with this proposed solution? Can I get more context on how the error happened in the first place?

Thanks for pointing out this problem.

**Comment by RumbleballTheReal** [comment] 2023-04-14 06:41
Hello, its a bit since I did that. Not sure what are all the changes I made, but here is the modified Script:

`///////////////////////////////////////////////////////////////////////////////
//                                                                           //
// Planar Reflections Probe for Unity's Built-in Render Pipeline             //
//                                                                           //
// Author: Rafael Bordoni                                                    //
// Date: January 25, 2022                                                    //
// Last Update: January 31, 2022                                             //
// Email: rafaelbordoni00@gmail.com                                          //
// Repository: https://github.com/eldskald/planar-reflections-unity          //
//                                                                           //
///////////////////////////////////////////////////////////////////////////////

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[ExecuteAlways, AddComponentMenu("Rendering/Planar Reflections Probe")]
public class PlanarReflectionsProbe : MonoBehaviour
{



    ///////////////////////////////////////////////////////////////////////////
    // Public properties that show up on the inspector.                      //
    ///////////////////////////////////////////////////////////////////////////

    [Range(1, 4)] public int targetTextureID = 1;
    private const string texName1 = "_PlanarReflectionsTex1";
    private const string texName2 = "_PlanarReflectionsTex2";
    private const string texName3 = "_PlanarReflectionsTex3";
    private const string texName4 = "_PlanarReflectionsTex4";

    [Space(10)]
    public bool useForwardAsNormal = false;
    public Vector3 planeNormal;
    public Vector3 planePosition;
    public LayerMask RenderLayers;
    [Space(10)]
    [Range(0.01f, 1.0f)] public float reflectionsQuality = 1f;
    public float farClipPlane = 1000;
    public float nearClipPlane = 0.3f;
    public bool renderBackground = true;
    [Space(10)]
    public bool renderInEditor = false;

    ///////////////////////////////////////////////////////////////////////////



    ///////////////////////////////////////////////////////////////////////////
    // Basic private methods and properties that control probe behavior,     //
    // both at runtime and at the editor.                                    //
    ///////////////////////////////////////////////////////////////////////////

    private GameObject _probeGO;
    private Camera _probe;
    private Skybox _probeSkybox;
    private ArrayList _ignoredCameras = new ArrayList();

    private Dictionary<Camera, RenderTexture> camTextureDict = new Dictionary<Camera, RenderTexture>();

    private void OnEnable()
    {
        Camera.onPreRender += PreRenderRoutine;
        Camera.onPostRender += PostRenderRoutine;
    }

    private void OnDisable()
    {
        FinalizeProbe();
        Camera.onPreRender -= PreRenderRoutine;
        Camera.onPostRender -= PostRenderRoutine;
    }

    private void OnDestroy()
    {
        FinalizeProbe();
        Camera.onPreRender -= PreRenderRoutine;
        Camera.onPostRender -= PostRenderRoutine;
    }

    private void InitializeProbe()
    {
        _probeGO = new GameObject("", typeof(Camera), typeof(Skybox));
        _probeGO.name = "PRCamera" + _probeGO.GetInstanceID().ToString();
        _probeGO.hideFlags = HideFlags.HideAndDontSave;
        _probe = _probeGO.GetComponent<Camera>();
        _probeSkybox = _probeGO.GetComponent<Skybox>();
        _probeSkybox.enabled = false;
        _probeSkybox.material = null;
    }

    private void FinalizeProbe()
    {
        CleanupRenderTextures();
        if (_probeGO)
        {
            if (Application.isEditor)
            {
                DestroyImmediate(_probeGO);
            }
            else
            {
                Destroy(_probeGO);
            }
        }
    }

    private bool CheckCamera(Camera cam)
    {
        if (cam.tag.Contains("MainCamera"))
        {
            return true;
        }
        else if (renderInEditor && cam.cameraType == CameraType.SceneView)
        {
            return true;
        }

        return false;
    }

    private void PreRenderRoutine(Camera cam)
    {
        if (!CheckCamera(cam))
        {
            return;
        }

        else if (_probe == null)
        {
            InitializeProbe();
        }

        Vector3 normal = GetNormal();
        UpdateProbeSettings(cam);
        CreateRenderTexture(cam);
        UpdateProbeTransform(cam, normal);
        CalculateObliqueProjection(normal);
        _probe.Render();
        _probe.targetTexture.SetGlobalShaderProperty(TextureIdToName(targetTextureID));
    }

    private string TextureIdToName(int id)
    {
        switch (id)
        {
            case 1: return texName1;
            case 2: return texName2;
            case 3: return texName3;
            case 4: return texName4;
        }
        return "ERROR";
    }

    private void PostRenderRoutine(Camera cam)
    {
        if (CheckCamera(cam) || _probe == null)
        {
            return;
        }
    }

    private void CleanupRenderTextures()
    {
        foreach (RenderTexture texture in camTextureDict.Values)
        {
            texture.Release();
        }
        camTextureDict.Clear();
    }

    ///////////////////////////////////////////////////////////////////////////



    ///////////////////////////////////////////////////////////////////////////
    // Auxiliary private methods called by the ones above. This is           //
    // where most of the math and other gritty details are.                  //
    ///////////////////////////////////////////////////////////////////////////

    private void UpdateProbeSettings(Camera cam)
    {
        RenderTexture texture = _probe.targetTexture;
        _probe.CopyFrom(cam);
        _probe.targetTexture = texture;
        _probe.enabled = false;
        _probe.cameraType = CameraType.Reflection;
        _probe.orthographic = false;
        _probe.usePhysicalProperties = false;
        _probe.farClipPlane = farClipPlane;
        _probe.nearClipPlane = nearClipPlane;
        _probe.cullingMask = RenderLayers;
        _probeSkybox.material = null;
        _probeSkybox.enabled = false;
        if (renderBackground)
        {
            _probe.clearFlags = cam.clearFlags;
            if (cam.GetComponent<Skybox>())
            {
                Skybox camSkybox = cam.GetComponent<Skybox>();
                _probeSkybox.material = camSkybox.material;
                _probeSkybox.enabled = camSkybox.enabled;
            }
        }
        else
        {
            //_probe.clearFlags = CameraClearFlags.Nothing;
            _probe.clearFlags = CameraClearFlags.Color;
            _probe.backgroundColor = Color.black;
        }
    }

    private void CreateRenderTexture(Camera cam)
    {
        int width = (int)((float)cam.pixelWidth * reflectionsQuality);
        int height = (int)((float)cam.pixelHeight * reflectionsQuality);

        RenderTexture texture = camTextureDict.GetValueOrDefault(cam, null);
        if (!texture || texture.width != width || texture.height != height)
        {
            Debug.Log("ReflectionProbe: Creating new RenderTexture: " + width.ToString() + "  " + height.ToString(), this);
            if (texture)
            {
                camTextureDict.Remove(cam);
                texture.Release();
            }

            _probe.targetTexture = new RenderTexture(width, height, 24);
            _probe.targetTexture.Create();
            camTextureDict.Add(cam, _probe.targetTexture);
        }
        else
        {
            _probe.targetTexture = texture;
        }
    }

    private Vector3 GetNormal()
    {
        if (useForwardAsNormal)
        {
            return transform.forward;
        }
        else if (planeNormal.Equals(Vector3.zero))
        {
            return Vector3.up;
        }
        else
        {
            return planeNormal.normalized;
        }
    }

    // The probe's camera position should be the the current camera's position
    // mirrored by the reflecting plane. Its rotation mirrored too.
    private void UpdateProbeTransform(Camera cam, Vector3 normal)
    {
        Vector3 proj = normal * Vector3.Dot(
            normal, cam.transform.position - planePosition);
        _probe.transform.position = cam.transform.position - 2 * proj;

        Vector3 probeForward = Vector3.Reflect(cam.transform.forward, normal);
        Vector3 probeUp = Vector3.Reflect(cam.transform.up, normal);
        _probe.transform.LookAt(
            _probe.transform.position + probeForward, probeUp);
    }

    // The clip plane should coincide with the plane with reflections.
    private void CalculateObliqueProjection(Vector3 normal)
    {
        Matrix4x4 viewMatrix = _probe.worldToCameraMatrix;
        Vector3 viewPosition = viewMatrix.MultiplyPoint(planePosition);
        Vector3 viewNormal = viewMatrix.MultiplyVector(normal);
        Vector4 plane = new Vector4(
            viewNormal.x, viewNormal.y, viewNormal.z,
            -Vector3.Dot(viewPosition, viewNormal));
        _probe.projectionMatrix = _probe.CalculateObliqueMatrix(plane);
    }

    ///////////////////////////////////////////////////////////////////////////



    ///////////////////////////////////////////////////////////////////////////
    // Public methods.                                                       //
    ///////////////////////////////////////////////////////////////////////////

    public void IgnoreCamera(Camera cam)
    {
        if (!_ignoredCameras.Contains(cam))
        {
            _ignoredCameras.Add(cam);
        }
    }

    public void UnignoreCamera(Camera cam)
    {
        if (_ignoredCameras.Contains(cam))
        {
            _ignoredCameras.Remove(cam);
        }
    }

    public void ClearIgnoredList()
    {
        _ignoredCameras.Clear();
    }

    public bool IsIgnoring(Camera cam)
    {
        return _ignoredCameras.Contains(cam);
    }

    ///////////////////////////////////////////////////////////////////////////



    ///////////////////////////////////////////////////////////////////////////
    // Static methods.                                                       //
    ///////////////////////////////////////////////////////////////////////////

    public static PlanarReflectionsProbe[] FindProbesRenderingTo(int id)
    {
        var probes = FindObjectsOfType<PlanarReflectionsProbe>();
        ArrayList list = new ArrayList();
        foreach (PlanarReflectionsProbe probe in probes)
        {
            if (probe.targetTextureID == id)
            {
                list.Add(probe);
            }
        }
        return (PlanarReflectionsProbe[])list.ToArray(
            typeof(PlanarReflectionsProbe));
    }

    public static PlanarReflectionsProbe FindProbeRenderingTo(int id)
    {
        var probes = FindObjectsOfType<PlanarReflectionsProbe>();
        foreach (PlanarReflectionsProbe probe in probes)
        {
            if (probe.targetTextureID == id)
            {
                return probe;
            }
        }
        return null;
    }

    ///////////////////////////////////////////////////////////////////////////
}

`

**Comment by eldskald** [comment] 2023-04-15 00:54
Hey, thank you for your code! So, comparing it to the current code I see what you meant, you made a hashtable to map each camera with a RenderTexture, just like your opening comment suggested. What confuses me is that each Camera already has that targetTexture property so I thought making such map would be unnecessary since we can access each camera's RenderTexture directly from this property. In fact, this was my first attempt, I would check if the camera's target texture had a different size or was null to know if I had to remake it but it didn't work, nothing would render and as I tinkered with it I even froze my editor with what I thought was a memory leak. No idea what caused that behavior but I'm happy you found that error because I think this hashtable is more performant. Do you have any idea why we can't just use the camera's targetTexture to do it? Why do we need a hashtable?

By the way I just checked and your code works fine. Thanks for this! I'm closing this issue since it's fixed, but if you have the answer to my question above you could send me an email with the answer if you wanted to. Thanks again!

**Closed as completed by eldskald** 2023-04-15 00:54 UTC
